package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"strings"
)

// Distributed load testing coordination protocol (plow cluster v1).
//
// A single controller manages many agents over HTTP/JSON:
//
//	agent -> controller : POST /plow/v1/register
//	agent -> controller : POST /plow/v1/heartbeat   (stats + ack piggyback)
//	agent -> controller : POST /plow/v1/deregister
//	controller -> agent : commands piggybacked on heartbeat/register
//	                     responses (prepare / set_rate / stop / abort)
//
// Every request/response carries protocol and result schema versions,
// and every schedule command carries a monotonically increasing epoch so
// that delayed or duplicated network messages can never be applied twice.

const (
	clusterProtocolVersion = 1
	clusterResultVersion   = 1

	// Agent lifecycle phases reported in heartbeats.
	agentPhaseInit    = "init"
	agentPhaseArmed   = "armed"
	agentPhaseRunning = "running"
	agentPhaseStopped = "stopped"
	agentPhaseError   = "error"

	// Controller test phases reported in heartbeat responses.
	testPhaseIdle      = "idle"
	testPhaseArmed     = "armed"
	testPhaseRunning   = "running"
	testPhaseFinishing = "finishing"
	testPhaseDone      = "done"
	testPhaseAborted   = "aborted"

	// Commands pushed by the controller.
	cmdPrepare = "prepare"
	cmdSetRate = "set_rate"
	cmdStop    = "stop"
	cmdAbort   = "abort"

	// Well known error codes returned to agents.
	errCodeVersionMismatch = "version_mismatch"
	errCodeResultMismatch  = "result_version_mismatch"
	errCodeConfigMismatch  = "config_hash_mismatch"
	errCodeBadRequest      = "bad_request"
	errCodeUnknownSession  = "unknown_session"
	errCodeStaleSession    = "stale_session"
	errCodeSeqGap          = "seq_gap"
	errCodeDuplicateNode   = "duplicate_node"
	errCodeNoTest          = "no_test"
)

// TestConfig is the immutable description of the benchmark generated by the
// controller and validated by every agent. The JSON serialization is
// canonical (fixed struct field order, no maps) so ConfigHash is stable.
type TestConfig struct {
	ProtocolVersion int `json:"protocol_version"`

	URL        string   `json:"url"`
	Method     string   `json:"method"`
	Headers    []string `json:"headers"`
	BodyB64    string   `json:"body_b64,omitempty"`
	BodyStream bool     `json:"body_stream,omitempty"`
	// BodyFile is only accepted for standalone runs: streaming a local file
	// from every remote node cannot be coordinated, so distributed runs must
	// inline the body.

	ContentType string `json:"content_type,omitempty"`
	Host        string `json:"host,omitempty"`
	Insecure    bool   `json:"insecure"`

	DoTimeoutNS    int64 `json:"do_timeout_ns"`
	ReadTimeoutNS  int64 `json:"read_timeout_ns"`
	WriteTimeoutNS int64 `json:"write_timeout_ns"`
	DialTimeoutNS  int64 `json:"dial_timeout_ns"`

	Socks5Proxy string `json:"socks5_proxy,omitempty"`
	HTTPProxy   string `json:"http_proxy,omitempty"`
	UnixSocket  string `json:"unix_socket,omitempty"`

	// Global budgets. The controller splits these across live nodes.
	Concurrency int     `json:"concurrency"`
	Rate        float64 `json:"rate"` // global requests per second, 0 == unlimited
	Requests    int64   `json:"requests"`
	DurationNS  int64   `json:"duration_ns"`
	RampUp      int     `json:"ramp_up"`
}

// ConfigHash fingerprints the exact configuration an agent is asked to run.
// It is computed over the canonical JSON encoding of the config itself.
func (c *TestConfig) ConfigHash() string {
	b, err := json.Marshal(c)
	if err != nil {
		// TestConfig is always JSON encodable.
		panic(fmt.Sprintf("cluster: marshal config: %v", err))
	}
	sum := sha256.Sum256(b)
	return hex.EncodeToString(sum[:])
}

// Validate checks semantic validity on both controller and agent sides.
func (c *TestConfig) Validate() error {
	if c.ProtocolVersion != clusterProtocolVersion {
		return fmt.Errorf("%s: config protocol %d, agent speaks %d",
			errCodeVersionMismatch, c.ProtocolVersion, clusterProtocolVersion)
	}
	if c.URL == "" {
		return fmt.Errorf("%s: missing target url", errCodeBadRequest)
	}
	if c.Concurrency < 1 {
		return fmt.Errorf("%s: concurrency must be >= 1", errCodeBadRequest)
	}
	if c.Rate < 0 {
		return fmt.Errorf("%s: rate must be >= 0", errCodeBadRequest)
	}
	if c.BodyStream {
		return fmt.Errorf("%s: streaming body file is not supported in distributed mode", errCodeBadRequest)
	}
	for _, h := range c.Headers {
		if strings.SplitN(h, ":", 2)[0] == h {
			return fmt.Errorf("%s: invalid header %q", errCodeBadRequest, h)
		}
	}
	return nil
}

// Command is a single scheduling instruction. Epoch is strictly increasing
// per controller session; agents ignore any command whose epoch is not newer
// than the last one they applied, which makes retries idempotent.
type Command struct {
	Epoch   int64  `json:"epoch"`
	Type    string `json:"type"`
	Reason  string `json:"reason,omitempty"`
	Version int    `json:"version"`

	Config *TestConfig `json:"config,omitempty"`
	Hash   string      `json:"hash,omitempty"`

	// Schedule in controller wall-clock domain (Unix nanoseconds).
	StartAtNS int64 `json:"start_at_ns,omitempty"`
	StopAtNS  int64 `json:"stop_at_ns,omitempty"`

	// Per-node budgets.
	Rate        float64 `json:"rate"` // 0 == unlimited
	Concurrency int     `json:"concurrency"`
	Quota       int64   `json:"quota"` // -1 == unbounded
}

// VerifyConfig recomputes the hash and validates versions. Called by agents
// before applying a prepare command so corrupted/tampered schedules cannot
// start traffic.
func (cmd *Command) VerifyConfig() (*TestConfig, error) {
	if cmd.Version != clusterResultVersion {
		return nil, fmt.Errorf("%s: command result version %d, agent version %d",
			errCodeResultMismatch, cmd.Version, clusterResultVersion)
	}
	if cmd.Type != cmdPrepare {
		return nil, fmt.Errorf("%s: not a prepare command", errCodeBadRequest)
	}
	cfg := cmd.Config
	if cfg == nil {
		return nil, fmt.Errorf("%s: prepare without config", errCodeBadRequest)
	}
	if err := cfg.Validate(); err != nil {
		return nil, err
	}
	if got := cfg.ConfigHash(); got != cmd.Hash {
		return nil, fmt.Errorf("%s: expected %s got %s", errCodeConfigMismatch, cmd.Hash, got)
	}
	return cfg, nil
}

// MsgRegister is sent by an agent when it (re)connects.
type MsgRegister struct {
	ProtocolVersion int      `json:"protocol_version"`
	ResultVersion   int      `json:"result_version"`
	PlowVersion     string   `json:"plow_version"`
	AgentID         string   `json:"agent_id"`
	SessionID       string   `json:"session_id,omitempty"` // set to resume
	Hostname        string   `json:"hostname"`
	Weight          float64  `json:"weight"`
	Capabilities    []string `json:"capabilities"`
	// T1NS is the agent wall-clock timestamp of the request; the controller
	// echoes T2/T3 so the agent already gets one clock sample from register.
	T1NS int64 `json:"t1_ns"`
}

// RegisterResponse returns the assigned session and, when the test is
// already running, the prepare command for a late joiner.
type RegisterResponse struct {
	ErrorCode string `json:"error_code,omitempty"`
	Message   string `json:"message,omitempty"`

	SessionID           string   `json:"session_id"`
	HeartbeatIntervalNS int64    `json:"heartbeat_interval_ns"`
	HeartbeatTimeoutNS  int64    `json:"heartbeat_timeout_ns"`
	T1NS                int64    `json:"t1_ns"`
	T2NS                int64    `json:"t2_ns"`
	T3NS                int64    `json:"t3_ns"`
	TestPhase           string   `json:"test_phase"`
	Command             *Command `json:"command,omitempty"`
}

// MsgHeartbeat carries liveness, clock quality, applied epoch and the latest
// cumulative stats. Seq is per-session, strictly increasing, and retried
// unchanged when the response is lost: the controller dedupes on (session,seq).
type MsgHeartbeat struct {
	ProtocolVersion int    `json:"protocol_version"`
	ResultVersion   int    `json:"result_version"`
	AgentID         string `json:"agent_id"`
	SessionID       string `json:"session_id"`
	Seq             int64  `json:"seq"`

	T1NS int64 `json:"t1_ns"`

	Phase      string `json:"phase"`
	AckedEpoch int64  `json:"acked_epoch"`

	// Clock quality as measured by the agent itself, used by the controller
	// to size the synchronized-start lead time.
	ClockOffsetNS   int64 `json:"clock_offset_ns"`
	ClockRTTNS      int64 `json:"clock_rtt_ns"`
	ClockDispersion int64 `json:"clock_dispersion_ns"`

	Stats *NodeStats `json:"stats,omitempty"`
	Error string     `json:"error,omitempty"`
}

// HeartbeatResponse returns fresh clock timestamps, the current test phase
// and the newest unacked command (prepare/set_rate/stop/abort).
type HeartbeatResponse struct {
	ErrorCode string `json:"error_code,omitempty"`
	Message   string `json:"message,omitempty"`

	T2NS      int64    `json:"t2_ns"`
	T3NS      int64    `json:"t3_ns"`
	TestPhase string   `json:"test_phase"`
	Command   *Command `json:"command,omitempty"`
	// StartAtNS/StopAtNS echo the authoritative test schedule even when no
	// command is pending, so reconnecting agents can re-arm themselves.
	StartAtNS int64 `json:"start_at_ns,omitempty"`
	StopAtNS  int64 `json:"stop_at_ns,omitempty"`
}

// MsgDeregister is sent on graceful agent shutdown.
type MsgDeregister struct {
	AgentID   string `json:"agent_id"`
	SessionID string `json:"session_id"`
	Reason    string `json:"reason,omitempty"`
}

// DeregisterResponse acknowledges graceful leave.
type DeregisterResponse struct {
	ErrorCode string `json:"error_code,omitempty"`
	Message   string `json:"message,omitempty"`
}

// versionsCompatible enforces exact protocol/result versions and a matching
// plow build ("dev" builds are treated as a wildcard for local development).
func versionsCompatible(agentProto, agentResult int, agentPlow string) error {
	if agentProto != clusterProtocolVersion {
		return fmt.Errorf("%s: agent protocol %d, controller %d",
			errCodeVersionMismatch, agentProto, clusterProtocolVersion)
	}
	if agentResult != clusterResultVersion {
		return fmt.Errorf("%s: agent result schema %d, controller %d",
			errCodeResultMismatch, agentResult, clusterResultVersion)
	}
	ap, cp := strings.TrimSpace(agentPlow), strings.TrimSpace(version)
	if ap == "" || ap == "dev" || cp == "" || cp == "dev" {
		return nil
	}
	if ap != cp {
		return fmt.Errorf("%s: agent plow %q, controller plow %q",
			errCodeVersionMismatch, ap, cp)
	}
	return nil
}
